"use client";
import { Navbar, FloatingWhatsapp } from "@/components";
import "./globals.css";
import { Inter } from "next/font/google";
import { GlobalContextProvider } from "@/components/Context";

const inter = Inter({ subsets: ["latin"] });
import Script from "next/script";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import { usePathname } from "next/navigation";
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();
  return (
    <>
      {/* {pathname !== "/paymentx" ? ( */}
      <GlobalContextProvider>
        <html lang="en" style={{ height: "100%" }}>
          <body className={inter.className}>
            <Script src="https://www.paytr.com/js/iframeResizer.min.js"></Script>
            <Navbar />
            {children}
            <FloatingWhatsapp />
          </body>
        </html>
      </GlobalContextProvider>
      {/* ) : (
        { children }
      )} */}
    </>
  );
}
